import { Craftsman, Booking, Category, Review } from './types'

export const categories: Category[] = [
  { id: '1', icon: 'droplets', labelAr: 'سباكة', labelEn: 'Plumbing', count: 245 },
  { id: '2', icon: 'zap', labelAr: 'كهرباء', labelEn: 'Electrical', count: 312 },
  { id: '3', icon: 'hammer', labelAr: 'نجارة', labelEn: 'Carpentry', count: 198 },
  { id: '4', icon: 'paint-bucket', labelAr: 'دهان', labelEn: 'Painting', count: 156 },
  { id: '5', icon: 'wind', labelAr: 'تكييف', labelEn: 'AC & Cooling', count: 89 },
  { id: '6', icon: 'wrench', labelAr: 'حدادة', labelEn: 'Welding', count: 67 },
  { id: '7', icon: 'grid-3x3', labelAr: 'بلاط', labelEn: 'Tiling', count: 124 },
  { id: '8', icon: 'sparkles', labelAr: 'تنظيف', labelEn: 'Cleaning', count: 203 },
]

export const craftsmen: Craftsman[] = [
  {
    id: '1',
    name: 'Ahmed Hassan',
    nameAr: 'أحمد حسن',
    specialty: 'Plumbing',
    specialtyAr: 'سباكة',
    avatar: 'https://i.pravatar.cc/150?img=1&s=150',
    coverPhoto: 'https://images.unsplash.com/photo-1581092163562-40460efbc3be?w=400&h=300&fit=crop',
    rating: 4.8,
    reviewCount: 127,
    distance: 2.3,
    isAvailable: true,
    tier: 'pro',
    verified: true,
    yearsExperience: 8,
    serviceAreas: ['Cairo', 'Giza', 'Helwan'],
    portfolio: [
      'https://images.unsplash.com/photo-1581092173320-8ef59ddb8107?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1581092166562-40460efbc3be?w=300&h=300&fit=crop',
    ],
    bio: 'Professional plumber with 8 years of experience',
    bioAr: 'سباك متخصص بخبرة ٨ سنوات',
    hourlyRate: 150,
    ratings: {
      punctuality: 4.9,
      cleanliness: 4.7,
      pricing: 4.6,
      quality: 4.9,
      attitude: 4.8,
    },
  },
  {
    id: '2',
    name: 'Fatima Al-Mansouri',
    nameAr: 'فاطمة المنصوري',
    specialty: 'Electrical Work',
    specialtyAr: 'أعمال كهربائية',
    avatar: 'https://i.pravatar.cc/150?img=5&s=150',
    coverPhoto: 'https://images.unsplash.com/photo-1621905167918-48416bd8575a?w=400&h=300&fit=crop',
    rating: 4.9,
    reviewCount: 203,
    distance: 1.8,
    isAvailable: true,
    tier: 'master',
    verified: true,
    yearsExperience: 12,
    serviceAreas: ['Cairo', 'New Cairo', 'Maadi'],
    portfolio: [
      'https://images.unsplash.com/photo-1621905167918-48416bd8575a?w=300&h=300&fit=crop',
    ],
    bio: 'Master electrician with certification',
    bioAr: 'كهربائي متقن معتمد',
    hourlyRate: 200,
    ratings: {
      punctuality: 5.0,
      cleanliness: 4.9,
      pricing: 4.8,
      quality: 5.0,
      attitude: 4.9,
    },
  },
  {
    id: '3',
    name: 'Mohamed Saad',
    nameAr: 'محمد سعد',
    specialty: 'Carpentry',
    specialtyAr: 'نجارة',
    avatar: 'https://i.pravatar.cc/150?img=3&s=150',
    coverPhoto: 'https://images.unsplash.com/photo-1577968917302-e90b9c59a852?w=400&h=300&fit=crop',
    rating: 4.7,
    reviewCount: 89,
    distance: 3.2,
    isAvailable: false,
    tier: 'skilled',
    verified: true,
    yearsExperience: 5,
    serviceAreas: ['Cairo', 'Giza'],
    portfolio: [
      'https://images.unsplash.com/photo-1577968917302-e90b9c59a852?w=300&h=300&fit=crop',
    ],
    bio: 'Skilled carpenter specializing in custom furniture',
    bioAr: 'نجار ماهر متخصص في الأثاث المخصص',
    hourlyRate: 120,
    ratings: {
      punctuality: 4.6,
      cleanliness: 4.8,
      pricing: 4.7,
      quality: 4.8,
      attitude: 4.5,
    },
  },
  {
    id: '4',
    name: 'Layla Ibrahim',
    nameAr: 'ليلى إبراهيم',
    specialty: 'Painting',
    specialtyAr: 'دهان',
    avatar: 'https://i.pravatar.cc/150?img=7&s=150',
    coverPhoto: 'https://images.unsplash.com/photo-1578926078328-123456789012?w=400&h=300&fit=crop',
    rating: 4.6,
    reviewCount: 67,
    distance: 4.1,
    isAvailable: true,
    tier: 'skilled',
    verified: true,
    yearsExperience: 4,
    serviceAreas: ['Cairo', 'Helwan'],
    portfolio: [],
    bio: 'Professional painter with attention to detail',
    bioAr: 'رسام احترافي يهتم بالتفاصيل',
    hourlyRate: 90,
    ratings: {
      punctuality: 4.5,
      cleanliness: 4.7,
      pricing: 4.6,
      quality: 4.6,
      attitude: 4.7,
    },
  },
  {
    id: '5',
    name: 'Omar Khalil',
    nameAr: 'عمر خليل',
    specialty: 'HVAC & Cooling',
    specialtyAr: 'تكييف وتبريد',
    avatar: 'https://i.pravatar.cc/150?img=2&s=150',
    coverPhoto: 'https://images.unsplash.com/photo-1555763365-82a8fb99e338?w=400&h=300&fit=crop',
    rating: 4.8,
    reviewCount: 134,
    distance: 1.5,
    isAvailable: true,
    tier: 'pro',
    verified: true,
    yearsExperience: 7,
    serviceAreas: ['Cairo', 'New Cairo', 'Maadi', 'Nasr City'],
    portfolio: [],
    bio: 'Expert in AC installation and maintenance',
    bioAr: 'خبير في تركيب وصيانة التكييف',
    hourlyRate: 180,
    ratings: {
      punctuality: 4.8,
      cleanliness: 4.9,
      pricing: 4.7,
      quality: 4.9,
      attitude: 4.8,
    },
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Noor Ahmed',
    authorAvatar: 'https://i.pravatar.cc/150?img=10&s=150',
    date: '2024-01-15',
    rating: 5,
    ratings: {
      punctuality: 5,
      cleanliness: 5,
      pricing: 4,
      quality: 5,
      attitude: 5,
    },
    text: 'Excellent work, very professional and on time',
    textAr: 'عمل ممتاز، احترافي جداً وفي الوقت المحدد',
    photos: [],
  },
  {
    id: '2',
    author: 'Sara Hassan',
    authorAvatar: 'https://i.pravatar.cc/150?img=11&s=150',
    date: '2024-01-10',
    rating: 4,
    ratings: {
      punctuality: 4,
      cleanliness: 5,
      pricing: 5,
      quality: 4,
      attitude: 4,
    },
    text: 'Good work, reasonable prices',
    textAr: 'عمل جيد، أسعار معقولة',
    photos: [],
  },
]

export const bookings: Booking[] = [
  {
    id: 'B001',
    craftsman: craftsmen[0],
    service: 'Pipe Repair',
    serviceAr: 'إصلاح الأنابيب',
    date: '2024-02-15',
    time: '10:00 AM',
    status: 'upcoming',
    address: '123 Main Street, Cairo',
    notes: 'Fix leaking kitchen faucet',
    totalAmount: 300,
    paymentMethod: 'card',
    photos: [],
  },
  {
    id: 'B002',
    craftsman: craftsmen[1],
    service: 'Electrical Inspection',
    serviceAr: 'فحص كهربائي',
    date: '2024-02-10',
    time: '2:00 PM',
    status: 'completed',
    address: '456 Nile Avenue, Cairo',
    notes: 'Check all outlets and switches',
    totalAmount: 400,
    paymentMethod: 'cash',
    photos: [],
  },
]

export const mockUser = {
  id: 'USER001',
  name: 'Ahmed Ali',
  nameAr: 'أحمد علي',
  phone: '+20 123 456 7890',
  email: 'ahmed@example.com',
  joinedDate: '2023-01-15',
  avatar: 'https://i.pravatar.cc/150?img=4&s=150',
  addresses: [
    {
      id: '1',
      label: 'Home',
      labelAr: 'المنزل',
      street: '123 Main Street',
      city: 'Cairo',
      zipCode: '12111',
      isDefault: true,
    },
    {
      id: '2',
      label: 'Office',
      labelAr: 'المكتب',
      street: '456 Business Park',
      city: 'New Cairo',
      zipCode: '11835',
      isDefault: false,
    },
  ],
}
